const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.video,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Tween,
		C3.Behaviors.Flash,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.video.Acts.SetPlaybackRate,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.video.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.video.Exps.PlaybackTime,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.video.Acts.SetPlaybackTime
	];
};
self.C3_JsPropNameTable = [
	{naStop: 0},
	{naStart: 0},
	{mgStop: 0},
	{mgStart: 0},
	{Fade: 0},
	{Video1: 0},
	{posX: 0},
	{posY: 0},
	{DragDrop: 0},
	{Tween: 0},
	{naBtn: 0},
	{mgBtn: 0},
	{dragArea: 0},
	{isFill: 0},
	{dragPlaceItem: 0},
	{dragItem: 0},
	{Video2: 0},
	{Video3: 0},
	{gunduzStop: 0},
	{lambOff: 0},
	{lambOn: 0},
	{Video4: 0},
	{Flash: 0},
	{hand: 0},
	{Browser: 0},
	{switchBox: 0},
	{onX: 0},
	{offX: 0},
	{switchBtn: 0},
	{Touch: 0},
	{fullScreenBtn: 0},
	{shareBtn: 0},
	{audioBtn: 0},
	{refreshBtn: 0},
	{Audio: 0},
	{katyonCount: 0},
	{videoPlaybackTime: 0},
	{soundControl: 0}
];

self.InstanceType = {
	Video1: class extends self.IWorldInstance {},
	naBtn: class extends self.ISpriteInstance {},
	mgBtn: class extends self.ISpriteInstance {},
	dragArea: class extends self.ISpriteInstance {},
	dragPlaceItem: class extends self.ISpriteInstance {},
	dragItem: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	Video3: class extends self.IWorldInstance {},
	Video4: class extends self.IWorldInstance {},
	hand: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	switchBox: class extends self.ISpriteInstance {},
	switchBtn: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {}
}